### PR TITLE
Fix/camera preview/rotation and size

### PR DESCRIPTION
**Pull request by noelsison**
### Updates
- Edited gradle files to allow building in Android Studio

#### Camera1.java
- Fix camera preview getting stretched ([cause](https://github.com/CameraKit/camerakit-android/commit/5875fded1b7bdac1bcc049fcc3accff4c0ac5cbf) as described in  CameraKit issue 288)
- Make `stopVideo()` return `true` on successful video record

#### SurfaceViewPreview.java
- Add `mSurfaceView.setZOrderMediaOverlay(true);` to make camera preview appear on top of other SurfaceViews (like videos)

#### CameraView.java and attrs.xml
- Added `ckDisableAutoRotate` option to disable orientation change events and fix the preview to portrait

### CODE REVIEW

**Comment by kgfig** [comment]
👍 Yey! Video recording problems solved! 

Okay to merge. Pa-add ng write permission din sa TickTockTechTalk repo. Thanks!

**Comment by noelsison** [comment]
@kgfig changed your organization role to "Owner" :ok_man:

**Comment by noelsison** [comment]
Output video is getting stretched

**Comment by noelsison** [comment]
> Output video is getting stretched

4cef14c66c5ffc393f551a90db16d1e1a502fa0e fixes this

**Pull request merged**
